<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "filereferenceupdatewizard"
 *
 * Auto generated by Extension Builder 2016-05-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'file_reference update wizard',
	'description' => 'migration wizards in core do not handle fields with internal_type of file_reference. This extension tries to fill the gap.',
	'category' => 'upgrade',
	'author' => 'Franz Kugelmann',
	'author_email' => 'franz.kugelmann@elementare-teilchen.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);